<a href="https://colab.research.google.com/github/wlj0504/Pytorch_study/blob/master/2_3%E7%BA%BF%E6%80%A7%E4%BB%A3%E6%95%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.3 线性代数

## 2.3.1 标量

变量(variable) 标量由只有一个元素的张量表示。



In [ ]:
import torch
x=torch.tensor(3.0)
y=torch.tensor(2.0)
x+y,x*y,x/y,x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 2.3.2 向量
向量可以被视为标量值组成的列表。这些组成了元素(element)或者分量(component)。

创建：

In [ ]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

通过张量的索引来访问任一元素。

In [ ]:
x[3]##x[0]=0，表示第0个位置的元素

tensor(3)

### 长度、维度、形状

向量的长度称为向量维度(dimension)。

我们可以调用Python内置函数len()函数来访问第0个轴的长度。

In [ ]:
len(x)

4

使用.shape的属性来访问向量的长度，或者说张量的每个轴的维度（长度）。

In [ ]:
x.shape

torch.Size([4])

x.ndim函数或者len(x.shape)才是判断张量有几个轴，也就是张量的维度，阶数。

In [ ]:
x.ndim

1

区分张量的维度和向量的维度：

张量：

shape[2,3,4]，三维，2x3x4

shape[4,5,6,7],四维

向量：

一个行上面有多少个分组
```
x=torch.tensor[[2,3,4],
    [1,2,3]]
```
是一个三维向量。

### 2.3.3 矩阵

方阵(square matrix)

创建：


In [ ]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置(transpose)

举例：


In [ ]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

特殊情况：
对称矩阵(symmetric matrix)本身等于自己的转置。


In [ ]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B)
B==B.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 2.3.4 张量
首先我们制造一个比较基础的张量：


In [ ]:
import torch
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 2.3.5 张量算法的基本性质

张量的运算是在各个元素上的运算。


In [ ]:
import torch
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵按照元素进行的乘积称作Hadamard积，数学符号是个圈中间有个点，代码上写为：

In [ ]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

另一个运算:



In [ ]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,a*X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

## 2.3.6 降维

对于一维张量（向量）中的元素进行加和。


In [ ]:
x =torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

二维张量（矩阵）的元素和。

In [ ]:
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

我们可以控制使得所有行的元素合并在不同轴，例如axis=0是列的数合并，axis=1是将每一行的数合并。

In [ ]:
A_sum_axis0=A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [ ]:
A_sum_axis1=A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [ ]:
A.sum(axis=[0,1]) ##沿着行和列一起求和，结果和A.sum()相同

tensor(190.)

求平均(mean/average)


In [ ]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

同样也可以按照指定轴降低维度

In [ ]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

 axis=0是按照行进行求和，即每一列从上到下加和起来，压缩为一列。

 axis=1是按照列进行求和，保留行，即每一行从左到右加和起来，然后shape变成（5，），但是这时候会进行处理，变成shape(1,5)样子，这时候我们想保持原样就需要补充keepdims=true。

In [4]:
import torch
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
sum_A=A.sum(axis=1,keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [6]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

其实上述就是每一行的归一化操作！


一个新的函数：cumsum()函数，这个函数不会按照任意轴的维度降低输入张量的维度。他会在每一行显示前置的求和。

In [7]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 2.3.7 点积
dot是点的意思，product是乘积。


In [8]:
x=torch.arange(4,dtype=torch.float32)
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

当然我们也可以手动模拟点乘，比如说先进行逐个元素的乘积然后加和。

In [9]:
torch.sum(x*y)

tensor(6.)

我们定义y为权重，并且权重为非负数并且求和为1，此时的点积就是我们意义上的加权求和。（weighted average）。

## 2.3.8 矩阵和向量积

矩阵-向量积（matrix-vector product）

在代码中，我们用mv函数来使用张量来表达矩阵-向量积，但是注意：A的列维度（沿轴1的长度）必须要与x的维度（长度）相同。

In [12]:
x=torch.arange(4,dtype=torch.float32)
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 2.3.9 范数
范数（norm）

我们定义范数f(x),需要满足一些性质：

1.f(αx)=|α| f(x)

2.f(x+y)=f(x)+f(y)

3.f(x)>=0,f(x)==0 iff 任意x的分量都为0

一般我们默认L2范数，即为||x||

In [14]:
u=torch.tensor([3.0,-4.0])
u.norm()

tensor(5.)

当然也是会经常有L1范数存在，L1范数相比较与L2范数来说收到异常值的影响比较小，计算L1函数时，我们需要如此：

In [15]:
torch.abs(u).sum()

tensor(7.)

abs（）是绝对值函数，sum是求和函数，所以结合起来就是L1范数。

当然矩阵也会有范数，比较经典的是Frobenius范数，是将矩阵内的所有元素平方加和，然后进行开根号。


In [16]:
torch.norm(torch.ones((4,9)))

tensor(6.)