<a href="https://colab.research.google.com/github/wlj0504/Pytorch_study/blob/master/2_1%E6%95%B0%E6%8D%AE%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 🤠2.1 数据操作
## 2.1.1 入门

首先第一步我们要import(导入)必需的 pytorch 库


In [18]:
import torch

我们可以创造一个元素全部为1的矩阵张量，用ones

In [19]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

生成一个随机的满足正态分布的张量，用randn

In [20]:
torch.randn((3,4))

tensor([[-0.1012, -1.4781, -0.1288, -1.4728],
        [ 1.7987,  1.1240,  0.7781, -0.0219],
        [-0.2065,  1.7848, -0.0796, -0.2983]])

提供包含数值的python列表，外层对应轴0，内层对应轴1

In [21]:
torch.tensor([[2,1,4,3],[4,5,6,7],[4,6,8,9]])

tensor([[2, 1, 4, 3],
        [4, 5, 6, 7],
        [4, 6, 8, 9]])

## 2.1.2运算符
### 1.基本的加减乘除

In [22]:
x=torch.tensor([0,1,2,3,4])
y=torch.tensor([9,8,7,6,5])
x+y,x-y,x*y,x/y,x**y

(tensor([9, 9, 9, 9, 9]),
 tensor([-9, -7, -5, -3, -1]),
 tensor([ 0,  8, 14, 18, 20]),
 tensor([0.0000, 0.1250, 0.2857, 0.5000, 0.8000]),
 tensor([   0,    1,  128,  729, 1024]))

### 2.向量concatenate（拼接）

API接口为torch.cat()，演示为两种接法，dim=0是按照形状的第一个元素对接，即为行。dim=1表示按照形状的第二个元素对接，即为列。

In [23]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

同时我们可以用X==Y来验证是否在各个位置相同

In [24]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

我们还可以通过对张量中的所有元素求和来产生一个单元素的张量。

In [25]:
X.sum()

tensor(66.)

### 2.1.3 broadcasting mechanism（广播机制）

用来解决形状不同的两个张量的操作

基本操作方法：

1.适当复制元素来进行扩充，使得两个张量具有相同的形状

2.对生成的数组执行按照元素的操作

In [27]:
a=torch.arange(4).reshape(4,1)
b=torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2],
         [3]]),
 tensor([[0, 1]]))

可以直接写加法，它会自动广播为4×2矩阵

In [29]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

### 2.1.4索引和切片
类似于python数组，我们可以索引元素

会用“，”来去区分切片的维度

In [36]:
# 0:3 表示切片：包含索引 0，但不包含索引 3 (即第 0, 1, 2 行)
a[-1], Y[0:3,:-2]

(tensor([3]),
 tensor([[2., 1.],
         [1., 2.],
         [4., 3.]]))


负数索引允许我们从张量的末尾向前索引：
- `-1`：最后一个元素
- `-2`：倒数第二个元素

切片公式依然遵循 `[start:end]`，即“包含开始，不包含结束”。


In [35]:
# 创建一个包含 0 到 9 的向量
z = torch.arange(10)
print(f"原始张量: {z}")

# 选取从索引 2 到倒数第 1 个元素 (不包含倒数第 1 个)
print(f"z[2:-1]: {z[2:-1]}")

# 选取最后 3 个元素
print(f"z[-3:]: {z[-3:]}")

# 选取从开始到倒数第 2 个元素 (不包含倒数第 2 个)
print(f"z[:-2]: {z[:-2]}")

# 在矩阵中使用负索引 (选取最后两行)
print(f"Y 最后两行:\n{Y[-2:]}")

原始张量: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
z[2:-1]: tensor([2, 3, 4, 5, 6, 7, 8])
z[-3:]: tensor([7, 8, 9])
z[:-2]: tensor([0, 1, 2, 3, 4, 5, 6, 7])
Y 最后两行:
tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])


我们还可以通过指定索引来将元素写入矩阵。

In [37]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

如果想为多个元素赋值相同的数值，我们可以索引所有元素，然后赋值。

In [38]:
X[0:2,:]=13
X

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [ 8.,  9., 10., 11.]])

### 2.1.5节省内存
我们使用Y=Y+X这种的操作方式，是将X和Y的值加和，并存储在一个全新的地址中占据内存，使得Y的指针指向这个新的地址。下例为验证：

In [42]:
before=id(Y)
Y=Y+X
id(Y)==before

False

我们可以使用切片赋值的方法，来实现节省内存


In [43]:
before=id(Y)
Y[:]=Y+X #Y+=X
id(Y)==before

True

### 2.1.6 转换为其他的python对象
将numpy数组转换为tensor张量

In [44]:
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

将tensor张量转换成为python标量，需要使用item函数或者python的内置函数

In [48]:
a=torch.tensor([4.5])
a,a.item(),float(a),int(a)

(tensor([4.5000]), 4.5, 4.5, 4)